#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/users/bssn/serna/github/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/users/bssn/serna/github/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/users/bssn/serna/HBP/SpineModel/mod/x86_64/.libs/libnrnmech.so" "$@"
